// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2wi8ujBbG1S8tiSHgV3n1zRbH8lqA7g8',
    appId: '1:649019361747:web:17510083bf32b3fc398726',
    messagingSenderId: '649019361747',
    projectId: 'bd-market-masters',
    authDomain: 'bd-market-masters.firebaseapp.com',
    storageBucket: 'bd-market-masters.appspot.com',
    measurementId: 'G-M90J0GKM7D',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO-gXAVQ8KoCzY4RXnnEVwqv__vmHbdWo',
    appId: '1:649019361747:ios:1e34a6d9a91b0a51398726',
    messagingSenderId: '649019361747',
    projectId: 'bd-market-masters',
    storageBucket: 'bd-market-masters.appspot.com',
    iosBundleId: 'com.example.bdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO-gXAVQ8KoCzY4RXnnEVwqv__vmHbdWo',
    appId: '1:649019361747:ios:1e34a6d9a91b0a51398726',
    messagingSenderId: '649019361747',
    projectId: 'bd-market-masters',
    storageBucket: 'bd-market-masters.appspot.com',
    iosBundleId: 'com.example.bdm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2wi8ujBbG1S8tiSHgV3n1zRbH8lqA7g8',
    appId: '1:649019361747:web:4aec08a4252adbe4398726',
    messagingSenderId: '649019361747',
    projectId: 'bd-market-masters',
    authDomain: 'bd-market-masters.firebaseapp.com',
    storageBucket: 'bd-market-masters.appspot.com',
    measurementId: 'G-HMYQBRF3DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKFar1TUsumEmTIoDWkE9901qfUtXOQhY',
    appId: '1:649019361747:android:9573ddb75ad19ce1398726',
    messagingSenderId: '649019361747',
    projectId: 'bd-market-masters',
    storageBucket: 'bd-market-masters.appspot.com',
  );

}